### ISSUE TITLE
[improvement] can add wechat for sharing plugin

### ISSUE THREAD

**Issue by stormtiti** [GitbookIO/plugin-sharing#6]
Hi guys,
I just wonder whether your plugin can add "WeChat" sharing link to gitbook ?
Here most of people use mobile phone to read articles via WeChat tool ;)
Thanks a lot ~~

Patrick

**Comment by Soreine** [comment]
Hello, I close this in favor of https://github.com/GitbookIO/plugin-sharing/issues/3
